
#' Convert to CalR
#'
#' @param calr_file a csv file generated by the sable macro
#' @param calr_headers a list of headers found in the data output from CalR
#'
#' @returns a data file in the CalR format

convert_to_calr <- function(calr_file, calr_headers){
  #prepare kcal name for regex
  calr_file <- calr_file |>
    dplyr::mutate(Date_Time_1 = as.POSIXct(Date_Time_1,
                                           format = "%m/%d/%Y %H:%M:%OS"))


  colnames(calr_file) <- stringr::str_replace(colnames(calr_file),
                                               pattern = "kcal_",
                                               replacement = "kcal-")

  #test for the various versions of macrooutput we might have
  if("envirolightlux_2"%in%colnames(calr_file)){
    long_sable <- calr_file |>
      dplyr::select(-DurationMin_1,
                    -envirorh_2,
                    -envirooccupancy_2,
                    -envirosound_2,
                    -envirotemp_2) |>
      dplyr::rename(envirolightlux_1 = envirolightlux_2)
  }

  else if("DurationMin_1"%in% colnames(calr_file)){
    long_sable <- calr_file |>
      dplyr::select(-DurationMin_1,
                    -envirorh_1,
                    -envirooccupancy_1)
  }

  else{
    long_sable <- calr_file |>
      dplyr::select(-durationmin,
                    -envirorh_1,
                    -envirooccupancy_11)
  }

  #convert time variables
  long_sable <- long_sable |>
    dplyr::mutate(elapsed_h = as.numeric(Date_Time_1-Date_Time_1[1])/3600,
                  elapsed_min = as.numeric(Date_Time_1-Date_Time_1[1])/60)



long_sable <- long_sable |>
  #remove noise from macro
  dplyr::filter(!is.na(Date_Time_1)) |>
  tidyr::pivot_longer(cols = -c("Date_Time_1",
                                "envirolightlux_1",
                                "envirosound_1",
                                "envirotemp_1",
                                "elapsed_h",
                                "elapsed_min"),
                      names_to = c("parameter","cage_id"),
                      names_sep = "_")|>
  tidyr::pivot_wider(names_from = "parameter",
                     values_from = "value")

long_sable <- long_sable |>
  #convert to more CalR resembling format
  dplyr::rename(ee = `kcal-hr`,
                feed.acc = foodupa,
                drink.acc = waterupa,
                subject.mass = bodymass,
                cage = cage_id,
                Date.Time = Date_Time_1,
                rer = rq,
                pedmeter = pedmeters,
                allmeter = allmeters,
                C13 = si13c,
                exp.minute = elapsed_min,
                exp.hour = elapsed_h,
                enviro.light = envirolightlux_1,
                enviro.temp = envirotemp_1,
                enviro.sound =envirosound_1
  ) |>
  dplyr::group_by(cage) |>
  dplyr::mutate(
    subject.id = as.character(cage),
    vo2 = vo2 * 60,
    #converts vo2 from ml/min to ml/h
    vco2 = vco2 * 60,
    ee.acc = cumsum(ee),
    feed = feed.acc - dplyr::lag(feed.acc, default = 0),
    drink = drink.acc - dplyr::lag(drink.acc, default = 0),
    xytot = xbreak + ybreak,
    xyamb = NA,
    wheel = NA,
    wheel.acc = NA,
    body.temp = -1,
    minute = lubridate::floor_date(Date.Time, unit = "minute"),
    hour = lubridate::floor_date(Date.Time, unit = "hour"),
    day = lubridate::floor_date(Date.Time, unit = "day"),
    exp.hour = floor(exp.hour),
    exp.day = floor(day - dplyr::first(day))
  ) |>
  dplyr::select(tidyr::all_of(calr_headers[-1]))

return(long_sable)
}

#' Group assigner
#'
#' @param session_file a calR session file
#'
#' @returns a data frame showing group distribution

group_assigner <- function(session_file){
  #detect how many groups we have
  group_vector <- stringr::str_subset(colnames(session_file),
                                      pattern = "group[:digit:]+")
  #extract group names
  group_names <- session_file |>
    dplyr::filter(!is.na(group_names)) |>
    dplyr::pull(group_names)

  #replace group names and make group overview
  group_info <- session_file |>
    dplyr::select(as.character(group_vector)) |>
    magrittr::set_colnames(group_names) |>
    tidyr::pivot_longer(cols = tidyselect::everything(),
                        values_to = "subject.id",
                        names_to = "group") |>
    dplyr::filter(!is.na(subject.id)) |>
    dplyr::mutate(subject.id= as.character(subject.id))
  return(group_info)
}

#' SEM calculator
#'
#' @param x a vector of values
#'
#' @returns calculated SEM

sem <- function(x){
  sem_value <- sd(x, na.rm = TRUE) / sqrt(length(!is.na(x)))
  return(sem_value)
}

#' Generate summary info
#'
#' @param calr a calR file in the calR format
#' @param session a session file
#' @param group_info a dataframe containing info on group distributions
#' @param resolution calculated resolution of the dataset
#'
#' @returns mean and SEM for various parameters

generate_summary_data <- function(calr, session, group_info, resolution){
  #remove ..1 col if it is there

  if("..1" %in% colnames(calr)){
    calr <- calr |>
      dplyr::select(-"..1")
  }

  calr_trimmed <- calr |>
    dplyr::select(-c('cage', 'xyamb', 'wheel', 'wheel.acc', 'day', 'hour',"C13","body.temp")) |>
    dplyr::mutate(subject.id = as.character(subject.id)) |>
    dplyr::left_join(group_info) |>
    #change to character if group is numeric
    dplyr::mutate(group = as.character(group)) |>
    dplyr::filter(exp.hour>= session$xrange[1] & exp.hour<session$xrange[2]+1,
                  #filter FI events above 100 mg/min
                  feed < 0.1 * resolution
                  ) |>
    #re-zero cumulative factors
    dplyr::group_by(subject.id) |>
    dplyr::mutate(
      allmeter = allmeter - dplyr::first(x = allmeter),
      exp.hour = exp.hour - dplyr::first(x = exp.hour),
      feed.acc = feed.acc - dplyr::first(x = feed.acc),
      drink.acc = drink.acc - dplyr::first(x = drink.acc),
      pedmeter = pedmeter - dplyr::first(x = pedmeter),
      exp.minute = exp.minute - dplyr::first(x = exp.minute))

  #make table of caloric content of food

  food_table <- session |>
    dplyr::select(group_names, dietCal) |>
    dplyr::mutate(group_names = as.character(group_names))

  #add food_table and adjust feed values

  ## DOUBLE CHECK THIS, THIS IS NOT RETURNING WHAT CALR IS RETURNING
  calr_trimmed <- calr_trimmed |>
    dplyr::left_join(food_table,
                     by = c("group"="group_names")) |>
    dplyr::mutate(
                  eb = (feed * dietCal) - ee/ (60/resolution),
                  eb.acc = cumsum(eb),
                  #convert feed grom g to kcal
                  feed = feed * dietCal,
                  feed.acc = cumsum(feed))|>
    dplyr::ungroup()

  #columns to use for calculations
  columns_to_use <- c("vo2","vco2","ee","ee.acc", "eb", "eb.acc", "rer","feed","feed.acc","drink","drink.acc","xytot",
                      "pedmeter","allmeter","enviro.light","enviro.temp")
  #overall group means and sem
  summary_calr <- calr_trimmed |>
    dplyr::group_by(subject.id) |>
    dplyr::reframe(
      dplyr::across(
        tidyr::all_of(columns_to_use),
        list(mean = ~mean(.x,
                          na.rm = TRUE),
             sem  = ~sem(.x)),
        .names = "{.col}_{.fn}"
      )) |>
    unique()

  #convert eb and food from kcal/interval to kcal/h

  summary_calr <- summary_calr |>
    dplyr::mutate(
      #convert from kcal/phase to kcal/h
      eb_mean = eb_mean * (60/resolution),
      eb.acc_mean = eb.acc_mean * (60/resolution),
      eb_sem = eb_sem * (60/resolution),
      eb.acc_sem  = eb.acc_sem * (60/resolution),
      feed_mean = feed_mean * (60/resolution),
      feed.acc_mean = feed.acc_mean * (60/resolution),
      feed_sem = feed_sem * (60/resolution),
      feed.acc_sem  = feed.acc_sem * (60/resolution)
    )

  #add total mass and group info
  mass_frame <- session |>
    dplyr::select(Total.Mass, id) |>
    dplyr::mutate(id= as.character(id))

  summary_calr <- summary_calr |>
    dplyr::left_join(mass_frame,
                     by = c("subject.id"="id")) |>
    dplyr::left_join(group_info)
}


#' calculate resolution
#'
#' @param data_set
#'
#' @returns calculated resolution

calculate_res <- function(data_set){
  res <- lubridate::minute(data_set$Date.Time[2])-lubridate::minute(data_set$Date.Time[1])
  res <- as.numeric(res)
  return(res)
}

#' Pull colors from session file
#'
#' @param session_file from calR
#'
#' @returns a data frame with group name and colors from calR
pull_colors <- function(session_file){
  #get the colors
  color_list <- session_file |>
    dplyr::select(group_names, colors)

  #save group_names
  group_vector <- color_list |>
    dplyr::filter(!is.na(group_names)) |>
    dplyr::pull(group_names)

  #check there are individuals in all groups

  group_info <- session_file |>
    dplyr::select(dplyr::all_of(
      stringr::str_subset(colnames(session_file),
                          pattern = "group[:digit:]+"))) |>
    magrittr::set_colnames(group_vector) |>
    dplyr::select(
      dplyr::where(~sum(!is.na(.)) > 0))

  color_list <- color_list |>
    dplyr::filter(group_names %in% colnames(group_info))


  return(color_list)
}


#' XY plotter
#'
#' @param summary_calr a calr summary object
#' @param color_key a dataframe with group names and color
#'
#' @returns a plotly object

xy_plotter <- function(summary_calr, color_key){
  xy_plot <- ggplot2::ggplot(summary_calr,
                             ggplot2::aes(
                               x = Total.Mass,
                               y = ee_mean,
                               color = group
                             ))+
    ggplot2::geom_point(size = 8)+
    ggplot2::scale_color_manual(values = color_key$colors)+
    ggplot2::theme_bw()

  xy_plot <- plotly::ggplotly(xy_plot)

  return(xy_plot)
}
