
#' Convert to CalR
#'
#' @param calr_file a csv file generated by the sable macro
#' @param calr_headers a list of headers found in the data output from CalR
#'
#' @returns a data file in the CalR format

convert_to_calr <- function(calr_file, calr_headers){
  #prepare kcal name for regex
  calr_file <- calr_file |>
    dplyr::mutate(Date_Time_1 = as.POSIXct(Date_Time_1,
                                           format = "%m/%d/%Y %H:%M:%OS"))


  colnames(calr_file) <- stringr::str_replace(colnames(calr_file),
                                               pattern = "kcal_",
                                               replacement = "kcal-")

  #test for the various versions of macrooutput we might have
  if("envirolightlux_2"%in%colnames(calr_file)){
    long_sable <- calr_file |>
      dplyr::select(-DurationMin_1,
                    -envirorh_2,
                    -envirooccupancy_2,
                    -envirosound_2,
                    -envirotemp_2) |>
      dplyr::rename(envirolightlux_1 = envirolightlux_2)
  }

  else if("DurationMin_1"%in% colnames(calr_file)){
    long_sable <- calr_file |>
      dplyr::select(-DurationMin_1,
                    -envirorh_1,
                    -envirooccupancy_1)
  }

  else{
    long_sable <- calr_file |>
      dplyr::select(-durationmin,
                    -envirorh_1,
                    -envirooccupancy_11)
  }

  #convert time variables
  long_sable <- long_sable |>
    dplyr::mutate(elapsed_h = as.numeric(Date_Time_1-Date_Time_1[1])/3600,
                  elapsed_min = as.numeric(Date_Time_1-Date_Time_1[1])/60)



long_sable <- long_sable |>
  #remove noise from macro
  dplyr::filter(!is.na(Date_Time_1)) |>
  tidyr::pivot_longer(cols = -c("Date_Time_1",
                                "envirolightlux_1",
                                "envirosound_1",
                                "envirotemp_1",
                                "elapsed_h",
                                "elapsed_min"),
                      names_to = c("parameter","cage_id"),
                      names_sep = "_")|>
  tidyr::pivot_wider(names_from = "parameter",
                     values_from = "value")

long_sable <- long_sable |>
  #convert to more CalR resembling format
  dplyr::rename(ee = `kcal-hr`,
                feed.acc = foodupa,
                drink.acc = waterupa,
                subject.mass = bodymass,
                cage = cage_id,
                Date.Time = Date_Time_1,
                rer = rq,
                pedmeter = pedmeters,
                allmeter = allmeters,
                C13 = si13c,
                exp.minute = elapsed_min,
                exp.hour = elapsed_h,
                enviro.light = envirolightlux_1,
                enviro.temp = envirotemp_1,
                enviro.sound =envirosound_1
  ) |>
  dplyr::group_by(cage) |>
  dplyr::mutate(
    subject.id = as.character(cage),
    vo2 = vo2 * 60,
    #converts vo2 from ml/min to ml/h
    vco2 = vco2 * 60,
    ee.acc = cumsum(ee),
    feed = feed.acc - dplyr::lag(feed.acc, default = 0),
    drink = drink.acc - dplyr::lag(drink.acc, default = 0),
    xytot = xbreak + ybreak,
    xyamb = NA,
    wheel = NA,
    wheel.acc = NA,
    body.temp = -1,
    minute = lubridate::floor_date(Date.Time, unit = "minute"),
    hour = lubridate::floor_date(Date.Time, unit = "hour"),
    day = lubridate::floor_date(Date.Time, unit = "day"),
    exp.hour = floor(exp.hour),
    exp.day = floor(day - dplyr::first(day))
  ) |>
  dplyr::select(tidyr::all_of(calr_headers[-1]))

return(long_sable)
}
